[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "atk", "cups", "libdrm", "libxkbcommon", "pango", "cairo", "alsa-lib"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
